### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by edp1096** [aaronbamberger/go-gerber-rs274x#1]
Hello, can I ask a question which license is using for this project?

**Comment by aaronbamberger** [comment]
I guess a BSD 2-Clause, I can update it to have a formal license, but I have to warn you, this code is ancient and unfinished, it was mostly just me screwing around with some stuff many years ago.  It doesn't parse the whole gerber spec, it uses regexes to do the parsing that it does do (which is almost certainly the wrong way to do it), the actual drawing code is unfinished and half-baked at best, the bottom line is basically I can't imagine this has any real usefulness to anybody.  This is mostly on github as a backup for a project I started and never finished that probably wouldn't have been very useful even if I'd finished it.

**Comment by edp1096** [comment]
Hello @aaronbamberger , thank you for notice.
It's enough to me for parsing Gerber X1, I would like to modify yours as base codes if you permit.

**Comment by aaronbamberger** [comment]
Absolutely, fork and modify to your heart's content.  I'll try and upload a license if I get some time (will be BSD 2-clause), but use it for whatever you want, with the caveat that it's not very good :)

**Comment by edp1096** [comment]
Thank you ! :)
